"use strict";

const fs = require("fs");
const path = require("path");
const babel = require("@babel/core");

const projectRoot = path.resolve(__dirname, "..");

const browserSources = [
  "data/airport-catalog.js",
  "config/settings.js",
  "config/posters.js",
  "models/states.js",
  "models/schedule-state.js",
  "models/operational-schedule-state.js",
  "models/live-flight-state.js",
  "App/state-engine.js",
  "App/visual-state-controller.js",
  "services/mock-flight-service.js",
  "services/calendar-api-service.js",
  "services/live-flight-api-service.js",
  "services/live-refresh-schedule.js",
  "services/calendar-state-controller.js",
  "App/instrument-math.js",
  "App/split-flap-audio.js",
  "App/map-roll-audio.js",
  "App/altitude-chime.js",
  "App/split-flap-state.js",
  "App/daily-schedule-layout.js",
  "App/deployment-refresh.js",
  "App/poster-image-loader.js",
  "App/airport-surface-map.js",
  "App/sequence-history-display.js",
  "App/weekly-ticker.js",
  "App/main.js",
  "App/daily-duty-card.js",
  "App/approved-map-artwork.js"
];

function readSource(relativePath) {
  return fs.readFileSync(
    path.join(projectRoot, relativePath),
    "utf8"
  );
}

const combinedSource = [
  ...browserSources.map(
    (relativePath) =>
      `\n/* Source: ${relativePath} */\n${readSource(relativePath)}`
  ),
  `\n/* Source: App/route-map.js (module scope preserved) */\n(function initializeDadRadarRouteMap() {\n${readSource("App/route-map.js")}\n})();`,
  `\n/* Source: App/map-roll-transition.js */\n${readSource("App/map-roll-transition.js")}`,
  `\n/* Source: App/descent-camera.js */\n${readSource("App/descent-camera.js")}`,
  `\n/* Source: App/sequence-history-map.js */\n${readSource("App/sequence-history-map.js")}`
].join("\n");

const result = babel.transformSync(
  combinedSource,
  {
    babelrc: false,
    configFile: false,
    comments: false,
    compact: false,
    presets: [
      [
        require.resolve("@babel/preset-env"),
        {
          bugfixes: true,
          modules: false,
          targets: "> 0.5%, not dead"
        }
      ]
    ],
    sourceType: "script"
  }
);

const outputPath = path.join(
  projectRoot,
  "App",
  "dad-radar-browser.js"
);

fs.writeFileSync(
  outputPath,
  `/* Generated by scripts/build-browser.js. Do not edit directly. */\n${result.code}\n`,
  "utf8"
);

console.log(
  `Built ${path.relative(projectRoot, outputPath)} for supported modern browsers.`
);

// Compact viewers use the identical transport/audio controller.
const rollBundle = babel.transformSync(
  readSource("App/map-roll-audio.js") + "\n" + readSource("App/map-roll-transition.js"), {
  babelrc:false, configFile:false, comments:false, presets:[[require.resolve("@babel/preset-env"),
    {bugfixes:true,modules:false,targets:"> 0.5%, not dead"}]], sourceType:"script"
});
fs.writeFileSync(path.join(projectRoot,"App/map-roll-browser.js"),rollBundle.code + "\n","utf8");
