"use strict";

const fs = require("fs");
const path = require("path");
const babel = require("@babel/core");

const projectRoot = path.resolve(__dirname, "..");

const browserSources = [
  "data/airport-catalog.js",
  "config/settings.js",
  "config/posters.js",
  "models/states.js",
  "models/schedule-state.js",
  "models/live-flight-state.js",
  "App/state-engine.js",
  "App/visual-state-controller.js",
  "services/mock-flight-service.js",
  "services/calendar-api-service.js",
  "services/live-flight-api-service.js",
  "services/calendar-state-controller.js",
  "App/instrument-math.js",
  "App/split-flap-audio.js",
  "App/split-flap-state.js",
  "App/daily-schedule-layout.js",
  "App/poster-image-loader.js",
  "App/main.js"
];

const compatibilityBootstrap = `
(function installDadRadarCompatibility(root) {
  "use strict";

  if (typeof root.globalThis === "undefined") {
    root.globalThis = root;
  }

  if (
    typeof root.Element !== "undefined" &&
    !root.Element.prototype.replaceChildren
  ) {
    root.Element.prototype.replaceChildren = function replaceChildren() {
      while (this.firstChild) {
        this.removeChild(this.firstChild);
      }

      for (var index = 0; index < arguments.length; index += 1) {
        var child = arguments[index];

        this.appendChild(
          child instanceof root.Node
            ? child
            : root.document.createTextNode(String(child))
        );
      }
    };
  }
})(window);
`;

function readSource(relativePath) {
  return fs.readFileSync(
    path.join(projectRoot, relativePath),
    "utf8"
  );
}

const combinedSource = [
  compatibilityBootstrap,
  ...browserSources.map(
    (relativePath) =>
      `\n/* Source: ${relativePath} */\n${readSource(relativePath)}`
  ),
  `\n/* Source: App/route-map.js (module scope preserved) */\n(function initializeDadRadarRouteMap() {\n${readSource("App/route-map.js")}\n})();`
].join("\n");

const result = babel.transformSync(
  combinedSource,
  {
    babelrc: false,
    configFile: false,
    comments: false,
    compact: false,
    presets: [
      [
        require.resolve("@babel/preset-env"),
        {
          bugfixes: true,
          forceAllTransforms: true,
          modules: false,
          targets: {
            ios: "9"
          }
        }
      ]
    ],
    sourceType: "script"
  }
);

const outputPath = path.join(
  projectRoot,
  "App",
  "dad-radar-browser.js"
);

fs.writeFileSync(
  outputPath,
  `/* Generated by scripts/build-browser.js. Do not edit directly. */\n${result.code}\n`,
  "utf8"
);

console.log(
  `Built ${path.relative(projectRoot, outputPath)} in legacy Safari-compatible ES5.`
);
